version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
      - "3000:3000"
    volumes:
      - ./courses:/home/app/autolab/courses
      - ./db:/home/app/autolab/db
